2 login logout
loitq/training pull request #6
Opened 2020-01-13 03:04 UTC by loitq

use laravel authentication

2020-01-13 06:13 UTC, minhtd92 commented on app/Http/Controllers/HomeController.php
> +     * @return void
Method not return any don't need return type at comment.

2020-01-13 06:14 UTC, minhtd92 commented on database/seeds/UsersTableSeeder.php
> +     * @return void
Method no need to add comment return type if it don't

2020-01-13 06:17 UTC, minhtd92 commented on resources/views/admin/index.blade.php
> +@endsection
Please end blank line at end of file

2020-01-13 06:20 UTC, minhtd92 commented
Why this file created but have not any data?
resources/views/admin/playout.blade.php

2020-01-13 06:21 UTC, minhtd92 commented on resources/views/user/index.blade.php
> +@endsection
Please add blank line at end of file

2020-01-13 06:32 UTC, phantuan1803 approved these changes
Review ok

2020-01-13 07:20 UTC, minhtd92 approved these changes
Reviewed ok!

2020-01-14 01:30 UTC, hienl requested changes
1) format cần chỉnh lại
branch : feature/xxxxxx
pull request : before merge pul request có name : [WIP][No-1][Training]xxxx[Review]

2) đã chạy qua phpcs phpmd chưa ? hãy gắn kết quả chạy vào Description

2020-01-14 01:30 UTC, hienl commented on app/Http/Controllers/Admin/AdminController.php
> +    }
Kiểm tra lại tất cả function trống , có thực sự cần thiết ? nếu không cần -> xóa

2020-01-14 01:30 UTC, hienl commented on app/Http/Controllers/Auth/LoginController.php
> +        if ($user->role == 1) {
không dùng '==' toàn bộ dùng '===' . không dùng trực tiếp value '1' , thay vào đó hãy tạo constant và sử dụng constant name

2020-01-14 01:30 UTC, hienl commented on database/migrations/2014_10_12_000000_create_users_table.php
> +            $table->unsignedTinyInteger('role')->default(2);
'2' là magic number , hãy dùng constant hoặc ít nhất comment ý nghĩa của '2'

2020-01-14 01:30 UTC, hienl commented on database/seeds/UsersTableSeeder.php
> +            'password' => Hash::make("lifull@123"),
role là giá trị quan trong , trừ trường hợp bất khả khán , khi tạo insert record đừng bỏ trống field này

2020-01-14 01:30 UTC, hienl commented on resources/js/components/ExampleComponent.vue
> +<template>
file này định dùng làm gì ?

2020-01-14 01:30 UTC, hienl commented on resources/js/app.js
> +Vue.component('example-component', require('./components/ExampleComponent.vue').default);
tại sao lại có code example trong project ?

2020-01-14 01:30 UTC, hienl commented on resources/views/auth/login.blade.php
> +                                        {{ __('Remember Me') }}
Chức năng nào của Lavarel hỗ trợ xử lý "Remember Me" ?

2020-01-14 01:30 UTC, hienl commented on resources/views/auth/passwords/email.blade.php
> +                                    {{ __('Send Password Reset Link') }}
Chức năng nào của Lavarel hỗ trợ xử lý send gì đó vào mail ?

2020-01-14 01:30 UTC, hienl commented on resources/views/auth/passwords/email.blade.php
> +                                </button>
template của mail reset password có thay đổi được không ?

2020-01-14 01:30 UTC, hienl commented on routes/web.php
> +     //Route User
tại sao space bị khác biệt so với 2 block code trên

2020-01-14 03:31 UTC, loitq commented on resources/js/app.js
> +Vue.component('example-component', require('./components/ExampleComponent.vue').default);
laravel hỗ trợ ui vue. khi e chạy lện command thì có có file này rùi anh. Để e xoá đi.

2020-01-14 03:34 UTC, loitq commented on resources/views/auth/passwords/email.blade.php
> +                                    {{ __('Send Password Reset Link') }}
za... để e thêm vào doc summary.

2020-01-14 03:37 UTC, loitq commented on resources/views/auth/passwords/email.blade.php
> +                                </button>
za dc anh...

2020-01-14 03:40 UTC, loitq commented on routes/web.php
> +     //Route User
e nghĩ admin và user xử lý khác nhau nên tách biệt 2 phần này.

2020-01-14 04:32 UTC, loitq commented on resources/views/auth/login.blade.php
> +                                        {{ __('Remember Me') }}
za... trong laravel authentication có hỗ trợ  Remembering Users... còn cách viết là show biến config trong laravel translation anh?.

2020-01-14 06:26 UTC, closed without merging